name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: iMusic
        ports:
          - 8889:3306 #map MySQL container's default port (3306) to 8889
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    # Checkout repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set environment variables
    - name: Set environment variables
      run: 
        echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "MYSQL_PORT=8889" >> $GITHUB_ENV
        echo "MYSQL_HOST=localhost" >> $GITHUB_ENV


    # Set up Node.js (Frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Adjust Node.js version as needed

    # Install frontend dependencies
    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: npm install

    # # Run frontend tests
    # - name: Run frontend tests
    #   working-directory: ./frontend
    #   run: npm test

    # Build frontend
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # Set up Python (Backend)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Adjust Python version as needed

    # Install Python dependencies
    - name: Install dependencies for backend
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run backend tests
    - name: Run backend tests
      working-directory: ./backend
      run: pytest
